=== Qiskit/qiskit/qiskit/schemas/backend_properties_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://www.qiskit.org/schemas/backend_props_schema.json",
    "description": "OpenQuantum backend properties schema",
    "version": "1.0.0",
    "definitions": {
        "gate": {
            "properties": {
                "gate": {
                    "type": "string"
                },
                "parameters": {
                    "items": {
                        "$ref": "#/definitions/nduv"
                    },
                    "minItems": 1,
                    "type": "array"
                },
                "qubits": {
                    "items": {
                        "type": "number"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            },
            "required": [
                "qubits",
                "gate",
                "parameters"
            ],
            "type": "object"
        },
        "general_parameters": {
            "description": "General system parameters",
            "items": {
                "$ref": "#/definitions/nduv"
            },
            "minItems": 0,
            "type": "array"
        },
        "nduv": {
            "description": "Recorded parameter as a name-date-unit-value",
            "properties": {
                "date": {
                    "format": "date-time",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            },
            "required": [
                "name",
                "date",
                "unit",
                "value"
            ],
            "type": "object"
        }
    },
    "description": "OpenQuantum backend properties schema",
    "properties": {
        "backend_name": {
            "description": "Backend name",
            "type": "string"
        },
        "backend_version": {
            "description": "Backend version in the form X.X.X",
            "pattern": "[0-9]+.[0-9]+.[0-9]+$",
            "type": "string"
        },
        "gates": {
            "description": "System gate parameters",
            "items": {
                "$ref": "#/definitions/gate"
            },
            "minItems": 1,
            "type": "array"
        },
        "general": {
            "$ref": "#/definitions/general_parameters"
        },
        "last_update_date": {
            "description": "Last date/time that a property was updated.",
            "format": "date-time",
            "type": "string"
        },
        "qubits": {
            "description": "System qubit parameters",
            "items": {
                "items": {
                    "$ref": "#/definitions/nduv"
                },
                "minItems": 1,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        }
    },
    "required": [
        "backend_name",
        "backend_version",
        "last_update_date",
        "qubits",
        "gates",
        "general"
    ],
    "type": "object",
    "version": "1.0.0"
}

=== Qiskit/qiskit/qiskit/schemas/examples/backend_properties_example.json
{
    "backend_name": "ibmqx5",
    "backend_version": "1.1.1",
    "last_update_date": "2018-04-02 15:00:00Z",
    "qubits": [
        [
            {"name": "T1", "date": "2018-04-02 15:00:00Z", "unit": "us", "value": 60},
            {"name": "T2", "date": "2018-04-02 15:00:00Z", "unit": "us", "value": 60},
            {"name": "frequency", "date": "2018-04-02 15:00:00Z", "unit": "GHz", "value": 5.2}
        ],
        [
            {"name": "T1", "date": "2018-04-02 15:00:00Z", "unit": "us", "value": 60},
            {"name": "T2", "date": "2018-04-02 15:00:00Z", "unit": "us", "value": 60},
            {"name": "frequency", "date": "2018-04-02 15:00:00Z", "unit": "us", "value": 5.2}
        ]
    ],
    "gates": [
        {"qubits": [0], "gate": "u2", "parameters": [
                {"name": "gateerr", "date": "2018-04-02 15:00:00Z", "unit": "None", "value": 0.002}]
        },
        {"qubits": [1], "gate": "u2", "parameters": [
                {"name": "gateerr", "date": "2018-04-02 15:00:00Z", "unit": "None", "value": 0.002}]
        },
        {"qubits": [0,1], "gate": "cx", "parameters": [
                {"name": "gateerr", "date": "2018-04-02 15:00:00Z", "unit": "None", "value": 0.02}]
        }],
    "general": [{"name": "fridge_temperature", "date": "2018-04-02 15:00:00Z", "unit": "mK", "value": 10}]
}
